// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BucketsProvider is an autogenerated mock type for the BucketsProvider type
type BucketsProvider struct {
	mock.Mock
}

// Buckets provides a mock function with given fields:
func (_m *BucketsProvider) Buckets() []float64 {
	ret := _m.Called()

	var r0 []float64
	if rf, ok := ret.Get(0).(func() []float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	return r0
}

// NewBucketsProvider creates a new instance of BucketsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBucketsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *BucketsProvider {
	mock := &BucketsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
