module-name: eventing-publisher-proxy
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/eventing-publisher-proxy:main
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
