name: Lint Markdown Links

on:
  pull_request:
    branches:
      - "main"
      - "release-*"
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'sec-scanners-config.yaml'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
          check-modified-files-only: 'yes'
          base-branch: ${{ github.base_ref }}
